### ISSUE TITLE
Проблема с установкой через pip.

### ISSUE THREAD

**Issue by nxbx** [Fahreeve/aiovk#1]
Co следующей ошибкой:
```
Downloading/unpacking aiovk
  Downloading aiovk-0.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/aiovk/setup.py) egg_info for package aiovk
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/aiovk/setup.py", line 5, in <module>
        version=__import__('aiovk').__version__,
      File "aiovk/__init__.py", line 1, in <module>
        from aiovk.sessions import ImplicitSession, TokenSession, AuthorizationCodeSession
      File "aiovk/sessions.py", line 21
        async def json(self, url, params, timeout=None):
                ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/aiovk/setup.py", line 5, in <module>

    version=__import__('aiovk').__version__,

  File "aiovk/__init__.py", line 1, in <module>

    from aiovk.sessions import ImplicitSession, TokenSession, AuthorizationCodeSession

  File "aiovk/sessions.py", line 21

    async def json(self, url, params, timeout=None):

            ^

SyntaxError: invalid syntax

```

**Comment by nxbx** [comment]
Прошу прощения, был установлен python 3.4
C python 3.5 все работает.
