### ISSUE TITLE
Не корректная обработка 911 ошибки(invalid keyboard)  

### ISSUE THREAD

**Issue by SvyatoslavSorokin** [Fahreeve/aiovk#37]
При возникновении ошибки invalid keyboard. Почему то возвращается UnknownVKException вместе с Traceback вместо VkAPIError.  
То, что возращает aiovk ниже.  
```pytohn
"['Traceback (most recent call last):',
 '  File "/app/src/sender/mailings/vk.py", line 131, in send_api_requestn    response = await super().send_api_request(*args, **kwargs)',
 '  File "/usr/local/lib/python3.6/site-packages/aiovk/sessions.py", line 92, in send_api_request    raise VkAPIError(error, self.REQUEST_URL + method_name)',
 'aiovk.exceptions.VkAPIError: ({'error_code': 911, 'error_msg': 'Keyboard format is invalid',
 'request_params': 
 [
 	{'key': 'oauth', 'value': '1'}, 
 	{'key': 'method', 'value': 'messages.send'}, 
 	{'key': 'user_ids', 'value': 'some user ids,some user ids'}, 
 	{'key': 'attachment', 'value': ''}, 
 	{'key': 'random_id', 'value': '50000001'}, 
	 	{'key': 'keyboard', 'value': 
	 		'{"buttons": [[{"color": "negative", "action": {"t": "text", "label": "YEAP", "payload": "{"button": "1"}"}}, {"color": "positive", "action": {"type": "text", "label": "KEK", "payload": "{"button": "2"}"}}], [{"color": "default", "action": {"type": "text", "label": "ROCHITA", "payload": "{"button": "3"}"}}, {"color": "primary", "action": {"type": "text", "label": "Blue", "payload": "{"button": "4"}"}}]], "one_time": true}'}, 
 	{'key': 'v', 'value': '5.74'}]}, 
 	'https://api.vk.com/method/messages.send')'
]
```

**Comment by DjHaski** [comment]
Вам черным по белому написано: `Keyboard format is invalid`. Смотрите формат клавиатуры которую вы посылаете.

**Comment by SvyatoslavSorokin** [comment]
Я намерено некорректную клавиатуру посылаю что бы написать обработку этой ошибки. По идеи должен возвращаться такой же объект VkAPIError как и при 900, 901, 902 ошибке например. А тут возвращается traceback будто скрипт упал а не возбуждает исключение

**Comment by DjHaski** [comment]
@Fahreeve Предлагаю закрыть Issue из-за отсутствия активности.
