### ISSUE TITLE
protocol is not None

### ISSUE THREAD

**Issue by jag-k** [Fahreeve/aiovk#38]
Уже который день пытаюсь запустить программу и ничего не получается (на данный момент вариант взят из вопросов):
```python
import asyncio

from aiovk import API
from aiovk import ImplicitSession
from aiovk.drivers import HttpDriver
from aiovk.mixins import LimitRateDriverMixin


class ExampleDriver(LimitRateDriverMixin, HttpDriver):
    requests_per_period = 3
    period = 1  # seconds


async def main():
    session = ImplicitSession("**Login**", "**Pwd**", Id, driver=ExampleDriver())
    api = API(session)
    a = await api.users.get(user_ids=1)
    await session.close()
    print(a)
    return a

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Всегда выбрасывает такую или подобную ошибку:

```
"C:\Program Files (x86)\Python37-32\python.exe" C:/Users/v8902/YandexDisk/Projects/VK-ESchool/__main__.py
Traceback (most recent call last):
  File "C:/Users/v8902/YandexDisk/Projects/VK-ESchool/__main__.py", line 23, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files (x86)\Python37-32\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:/Users/v8902/YandexDisk/Projects/VK-ESchool/__main__.py", line 17, in main
    a = await api.users.get(user_ids=1)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\aiovk\api.py", line 31, in __call__
    timeout,
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\aiovk\sessions.py", line 72, in send_api_request
    response = await self.driver.json(self.REQUEST_URL + method_name, params, timeout)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\aiovk\utils.py", line 28, in wrapper
    return await func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\aiovk\mixins.py", line 14, in json
    return await super().json(*args, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\aiovk\drivers.py", line 79, in json
    async with self.session.get(url, params=params, timeout=timeout or self.timeout) as response:
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\aiohttp\client.py", line 932, in __aenter__
    self._resp = await self._coro
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\aiohttp\client.py", line 424, in _request
    await resp.start(conn)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\aiovk\drivers.py", line 21, in start
    await super().start(connection, read_until_eof)
TypeError: start() takes 2 positional arguments but 3 were given
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x045550B0>
Task exception was never retrieved
future: <Task finished coro=<ClientRequest.write_bytes() done, defined at C:\Program Files (x86)\Python37-32\lib\site-packages\aiohttp\client_reqrep.py:515> exception=AssertionError()>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\aiohttp\client_reqrep.py", line 524, in write_bytes
    assert protocol is not None
AssertionError

Process finished with exit code 1
```

Что я делаю не так?
Версия Python 3.7

**Comment by DjHaski** [comment]
Последний aiohttp не поддерживается. #30

**Comment by Fahreeve** [comment]
доступна новая версия либы с поддержкой aiohttp 3.2+
https://pypi.org/project/aiovk/3.0.0/
